# Generated by Django 3.1 on 2020-09-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('reason', models.TextField()),
                ('pid', models.IntegerField()),
                ('stage', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('current', models.IntegerField()),
                ('total', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes', models.IntegerField(default=1)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
        ),
    ]
