# Generated by Django 3.1 on 2020-09-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_task_taskconfig_taskmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('none', 'None'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('succeeded', 'Finished')], default='none', max_length=200),
        ),
    ]
