# Generated by Django 3.1 on 2020-09-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmessage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taskmessage',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmessage',
            name='stage',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TaskStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('none', 'None'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('succeeded', 'Finished')], default='none', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('current', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
