# Generated by Django 3.1 on 2020-09-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200905_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmessage',
            name='finished',
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='state',
            field=models.CharField(choices=[('none', 'None'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('succeeded', 'Finished')], default='none', max_length=200),
        ),
    ]
