# Generated by Django 3.1 on 2020-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200906_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmessage',
            name='state',
            field=models.CharField(choices=[('none', 'None'), ('running', 'Running'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('succeeded', 'Finished')], default='none', max_length=200, null=True),
        ),
    ]
